server:
  port: 8050

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms1_simulation
          uri: lb://MS1SIMULATION
          predicates:
            - Path=/api/loan/simulate/**
        - id: ms2_register
          uri: lb://MS2REGISTER
          predicates:
            - Path=/api/user/**
        - id: ms3_request
          uri: lb://MS3REQUEST
          predicates:
            - Path=/api/loan/**
        - id: ms4_evaluation
          uri: lb://MS4EVALUATION
          predicates:
            - Path=/api/evaluation/**
        - id: ms5_follow
          uri: lb://MS5FOLLOW
          predicates:
            - Path=/api/follow/**
        - id: ms6_calculation
          uri: lb://MS6CALCULATION
          predicates:
            - Path=/api/calculation/**

      httpclient:
        connect-timeout: 5000
        response-timeout: 10000

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
